const c=document.getElementById("game"),x=c.getContext("2d"),S=document.getElementById("score"),L=document.getElementById("lives"),I=document.getElementById("items"),T=document.getElementById("status"),O=document.getElementById("overlay"),OT=document.getElementById("overlayTitle"),OX=document.getElementById("overlayText"),ST=document.getElementById("start");
const M=["#####################","#.........#.........#","#.###.###.#.###.###.#","#o#...#...#...#...#o#","#.#.###.#.#.#.###.#.#","#...#...#...#...#...#","###.#.#####.#####.#.#","#...#.....#.....#...#","#.#####.#.#.#.#####.#","#.......#...#.......#","#.#####.#####.#####.#","#...#.....#.....#...#","#.#.#.###.#.###.#.#.#","#o..#...#...#...#..o#","#.###.#.#####.#.###.#","#.........#.........#","#####################"],R=M.length,C=M[0].length,Q=c.width/C;
let p,e,it,score,lives,run,boost=0,last=0,keys={};
function reset(){score=0;lives=3;boost=0;p={x:1.5,y:1.5,d:{x:0,y:0},n:{x:1,y:0}};e=[{x:19.5,y:1.5,col:"#ff5577",s:2.35},{x:19.5,y:15.5,col:"#ffb84d",s:2.15},{x:1.5,y:15.5,col:"#b878ff",s:2.2}];it=[];for(let y=0;y<R;y++)for(let z=0;z<C;z++)if(M[y][z]=="."&&Math.random()<.2)it.push({x:z+.5,y:y+.5,t:0});else if(M[y][z]=="o")it.push({x:z+.5,y:y+.5,t:1});hud()}
function wall(x,y){return x<0||y<0||x>=C||y>=R||M[Math.floor(y)][Math.floor(x)]=="#"}
function free(q,dx,dy){return !wall(q.x+dx*.24,q.y+dy*.24)&&!wall(q.x+dx*.24,q.y-dy*.24)}
function move(q,dx,dy,s,dt){let a=s*dt,nx=q.x+dx*a,ny=q.y+dy*a;if(!wall(nx,ny)&&!wall(nx+Math.sign(dx)*.23,ny)&&!wall(nx,ny+Math.sign(dy)*.23)){q.x=nx;q.y=ny;return true}return false}
function dir(q,target){let ds=[[1,0],[-1,0],[0,1],[0,-1]].filter(d=>free(q,d[0],d[1]));ds.sort((a,b)=>Math.hypot(q.x+a[0]-target.x,q.y+a[1]-target.y)-Math.hypot(q.x+b[0]-target.x,q.y+b[1]-target.y));return ds[Math.random()<.25?Math.floor(Math.random()*ds.length):0]||[0,0]}
function hud(){S.textContent=score;L.textContent=lives;I.textContent=(it?it.length:0)+" left";T.textContent=performance.now()<boost?"BOOST!":run?"HUNTING":"READY"}
function update(dt){if(free(p,p.n.x,p.n.y))p.d=p.n;if(!move(p,p.d.x,p.d.y,performance.now()<boost?5.5:3.8,dt))p.d={x:0,y:0};
it=it.filter(a=>{if(Math.hypot(a.x-p.x,a.y-p.y)<.42){score+=a.t?250:100;if(a.t)boost=performance.now()+6000;return false}return true});
e.forEach(q=>{q.t=(q.t||0)-dt;if(q.t<=0||!move(q,q.d?.[0]||0,q.d?.[1]||0,q.s,dt)){q.d=dir(q,p);q.t=.35+Math.random()*.6}if(Math.hypot(q.x-p.x,q.y-p.y)<.48){lives--;score=Math.max(0,score-150);p.x=1.5;p.y=1.5;p.d={x:0,y:0}}});if(lives<=0)end(false);if(!it.length)end(true);hud()}
function end(w){run=false;OT.textContent=w?"MAZE CLEARED!":"GAME OVER";OX.textContent=w?"You collected everything. Score: "+score:"The chasers got you. Score: "+score;ST.textContent="Play Again";O.classList.remove("hidden");}
function draw(){x.fillStyle="#050712";x.fillRect(0,0,720,720);for(let y=0;y<R;y++)for(let z=0;z<C;z++)if(M[y][z]=="#"){x.fillStyle="#171d3d";x.fillRect(z*Q,y*Q,Q,Q);x.strokeStyle="#27305d";x.strokeRect(z*Q+.5,y*Q+.5,Q-1,Q-1)}it.forEach(a=>{x.fillStyle=a.t?"#6df6ff":"#ffe66d";x.beginPath();x.arc(a.x*Q,a.y*Q,a.t?Q*.2:Q*.1,0,7);x.fill()});e.forEach(q=>{x.fillStyle=q.col;x.beginPath();x.arc(q.x*Q,q.y*Q,Q*.27,0,7);x.fill();x.fillStyle="#fff";x.beginPath();x.arc(q.x*Q-Q*.09,q.y*Q-Q*.04,Q*.07,0,7);x.arc(q.x*Q+Q*.09,q.y*Q-Q*.04,Q*.07,0,7);x.fill()});x.fillStyle="#68ff9b";x.beginPath();x.arc(p.x*Q,p.y*Q,Q*.29,0,7);x.fill()}
function loop(t){let dt=Math.min((t-last)/1000,.05);last=t;if(run)update(dt);draw();requestAnimationFrame(loop)}
function start(){reset();run=true;O.classList.add("hidden");last=performance.now()}
addEventListener("keydown",a=>{let d={w:[0,-1],arrowup:[0,-1],s:[0,1],arrowdown:[0,1],a:[-1,0],arrowleft:[-1,0],d:[1,0],arrowright:[1,0]}[a.key.toLowerCase()];if(d){a.preventDefault();p.n={x:d[0],y:d[1]}}if(a.key.toLowerCase()=="r")start()});ST.onclick=start;document.getElementById("restart").onclick=start;reset();requestAnimationFrame(loop);